import { Node, Edge } from '@xyflow/react';

export type ServiceNodeData = {
  label: string;
  subtitle: string;
  color: 'blue' | 'green' | 'orange' | 'purple' | 'gray';
  description: string;
  techStack: string[];
  endpoints: { label: string; href: string }[];
  designDocs: { label: string; href: string }[];
  repoUrl: string;
};

export type ArchNode = Node<ServiceNodeData, 'service'>;
export type ArchEdge = Edge<{ label?: string; edgeType: 'http' | 'event' | 'storage' | 'browser' }>;

export const initialNodes: ArchNode[] = [
  {
    id: 'browser',
    type: 'service',
    position: { x: 440, y: 0 },
    data: {
      label: 'User Browser',
      subtitle: 'Client',
      color: 'blue',
      description: 'The end-user\'s browser runs the React SPA delivered by Azure Static Web Apps. All routing is client-side; the SWA config rewrites every path to index.html for deep-link support.',
      techStack: ['Chrome', 'Firefox', 'Safari'],
      endpoints: [],
      designDocs: [],
      repoUrl: '',
    },
  },
  {
    id: 'my-website',
    type: 'service',
    position: { x: 340, y: 140 },
    data: {
      label: 'my-website',
      subtitle: 'Azure Static Web Apps',
      color: 'blue',
      description: 'React 18 + TypeScript SPA. Six routes: landing, Digits puzzle, NBA momentum finder, trail finder, dashboard, and ideas board. Uses MSAL for auth-gated features.',
      techStack: ['React 18', 'TypeScript', 'React Router v6', 'Framer Motion', 'MSAL', 'Azure Static Web Apps'],
      endpoints: [
        { label: 'src/index.js — router', href: 'https://github.com/skarumbu/my-website/blob/main/src/index.js' },
        { label: 'src/Ideas.tsx — ideas board', href: 'https://github.com/skarumbu/my-website/blob/main/src/Ideas.tsx' },
        { label: 'src/Dashboard.tsx', href: 'https://github.com/skarumbu/my-website/blob/main/src/Dashboard.tsx' },
        { label: 'public/staticwebapp.config.json', href: 'https://github.com/skarumbu/my-website/blob/main/public/staticwebapp.config.json' },
      ],
      designDocs: [],
      repoUrl: 'https://github.com/skarumbu/my-website',
    },
  },
  {
    id: 'digits',
    type: 'service',
    position: { x: 0, y: 360 },
    data: {
      label: 'digits',
      subtitle: 'Azure Functions · Python 3.11',
      color: 'green',
      description: 'Generates and serves daily Digits math puzzles. The solver uses depth-first search with integer division constraints. Writes a metrics row to Table Storage on each request.',
      techStack: ['Azure Functions v2', 'Python 3.11', 'Azure Table Storage'],
      endpoints: [
        { label: 'GET /api/DigitsGetter', href: 'https://github.com/skarumbu/digits/blob/main/function_app.py' },
        { label: 'digits_creator.py — puzzle generation', href: 'https://github.com/skarumbu/digits/blob/main/digits_creator.py' },
        { label: 'digits_solver.py — DFS solver', href: 'https://github.com/skarumbu/digits/blob/main/digits_solver.py' },
        { label: 'nodes.py — grid/adjacency logic', href: 'https://github.com/skarumbu/digits/blob/main/nodes.py' },
      ],
      designDocs: [],
      repoUrl: 'https://github.com/skarumbu/digits',
    },
  },
  {
    id: 'momentum_finder',
    type: 'service',
    position: { x: 220, y: 360 },
    data: {
      label: 'momentum_finder',
      subtitle: 'Azure Container Apps · FastAPI',
      color: 'orange',
      description: 'Analyses live NBA game data to surface momentum shifts using a logistic regression model. Scales 0–10 replicas via KEDA. Model auto-retrains every Monday via a Container App Job.',
      techStack: ['FastAPI', 'Python 3.11', 'Azure Container Apps', 'Log Analytics', 'scikit-learn', 'nba_api'],
      endpoints: [
        { label: 'GET /get-current-games', href: 'https://github.com/skarumbu/momentum_finder/blob/main/server.py' },
        { label: 'GET /get-momentum', href: 'https://github.com/skarumbu/momentum_finder/blob/main/server.py' },
        { label: 'GET /health', href: 'https://github.com/skarumbu/momentum_finder/blob/main/server.py' },
        { label: 'model_trainer.py', href: 'https://github.com/skarumbu/momentum_finder/blob/main/model_trainer.py' },
        { label: 'retriever.py — nba_api integration', href: 'https://github.com/skarumbu/momentum_finder/blob/main/retriever.py' },
      ],
      designDocs: [],
      repoUrl: 'https://github.com/skarumbu/momentum_finder',
    },
  },
  {
    id: 'trail_finder',
    type: 'service',
    position: { x: 450, y: 360 },
    data: {
      label: 'trail_finder',
      subtitle: 'Azure Container Apps · FastAPI',
      color: 'blue',
      description: 'Given a city, fetches trails via Google Places, weather from Open-Meteo, AllTrails snippets via Google Custom Search, then synthesizes conditions with Azure OpenAI. 24h in-memory cache.',
      techStack: ['FastAPI', 'Python 3.11', 'Azure Container Apps', 'Google Places API', 'Open-Meteo', 'Azure OpenAI', 'Log Analytics'],
      endpoints: [
        { label: 'GET /get-trail-recommendations', href: 'https://github.com/skarumbu/trail_finder/blob/main/main.py' },
        { label: 'GET /autocomplete', href: 'https://github.com/skarumbu/trail_finder/blob/main/main.py' },
        { label: 'GET /health', href: 'https://github.com/skarumbu/trail_finder/blob/main/main.py' },
      ],
      designDocs: [],
      repoUrl: 'https://github.com/skarumbu/trail_finder',
    },
  },
  {
    id: 'ideas_api',
    type: 'service',
    position: { x: 680, y: 360 },
    data: {
      label: 'ideas-api',
      subtitle: 'Azure Functions · Python 3.11',
      color: 'purple',
      description: 'Stores and serves AI-generated feature ideas in Azure Table Storage. Accepts EasyAuth (browser JWT) or a machine write-key. Triggers the ideas-bot Container App Job.',
      techStack: ['Azure Functions v2', 'Python 3.11', 'Azure Table Storage', 'EasyAuth', 'Managed Identity'],
      endpoints: [
        { label: 'GET /api/ideas', href: 'https://github.com/skarumbu/ideas-api/blob/main/function_app.py#L97' },
        { label: 'POST /api/ideas', href: 'https://github.com/skarumbu/ideas-api/blob/main/function_app.py#L116' },
        { label: 'PATCH /api/ideas/{id}/bot', href: 'https://github.com/skarumbu/ideas-api/blob/main/function_app.py#L194' },
        { label: 'POST /api/ideas/{id}/run-bot', href: 'https://github.com/skarumbu/ideas-api/blob/main/function_app.py#L222' },
        { label: 'GET/POST /api/projects', href: 'https://github.com/skarumbu/ideas-api/blob/main/function_app.py#L61' },
        { label: 'ideas.py — Table Storage CRUD', href: 'https://github.com/skarumbu/ideas-api/blob/main/ideas.py' },
      ],
      designDocs: [],
      repoUrl: 'https://github.com/skarumbu/ideas-api',
    },
  },
  {
    id: 'dashboard_api',
    type: 'service',
    position: { x: 900, y: 360 },
    data: {
      label: 'dashboard_api',
      subtitle: 'Azure Functions · Python 3.11',
      color: 'purple',
      description: 'Aggregates health checks, Log Analytics metrics, Digits Table Storage metrics, and Azure Cost Management MTD spend across all services. Uses Managed Identity — no stored credentials.',
      techStack: ['Azure Functions v2', 'Python 3.11', 'Managed Identity', 'azure-monitor-query', 'Azure Cost Management', 'azure-mgmt-resourcegraph'],
      endpoints: [
        { label: 'GET /api/DashboardGetter', href: 'https://github.com/skarumbu/dashboard_api/blob/main/function_app.py' },
        { label: 'GET /api/discover', href: 'https://github.com/skarumbu/dashboard_api/blob/main/function_app.py' },
        { label: 'GET /api/apps', href: 'https://github.com/skarumbu/dashboard_api/blob/main/function_app.py' },
        { label: 'POST /api/apps', href: 'https://github.com/skarumbu/dashboard_api/blob/main/function_app.py' },
        { label: 'discovery.py — Resource Graph OBO', href: 'https://github.com/skarumbu/dashboard_api/blob/main/discovery.py' },
        { label: 'health_checks.py', href: 'https://github.com/skarumbu/dashboard_api/blob/main/health_checks.py' },
      ],
      designDocs: [],
      repoUrl: 'https://github.com/skarumbu/dashboard_api',
    },
  },
  {
    id: 'ideas_bot',
    type: 'service',
    position: { x: 680, y: 540 },
    data: {
      label: 'ideas-bot',
      subtitle: 'Container App Job · Python',
      color: 'gray',
      description: 'Autonomous agent triggered by ideas-api. Clones the target repo, runs a GPT-4o tool-use loop to implement the feature, commits, and opens a draft PR on GitHub.',
      techStack: ['Python 3.11', 'Azure Container App Job', 'Azure OpenAI (GPT-4o)', 'GitHub API'],
      endpoints: [
        { label: 'bot.py — main orchestrator', href: 'https://github.com/skarumbu/ideas-bot/blob/main/bot.py' },
        { label: 'Dockerfile', href: 'https://github.com/skarumbu/ideas-bot/blob/main/Dockerfile' },
      ],
      designDocs: [],
      repoUrl: 'https://github.com/skarumbu/ideas-bot',
    },
  },
  {
    id: 'azure_infrastructure',
    type: 'service',
    position: { x: 340, y: 560 },
    data: {
      label: 'azure-infrastructure',
      subtitle: 'Bicep · Subscription scope',
      color: 'gray',
      description: 'Provisions all Azure resources: Static Web App, Container Registry, shared Container App Environment (+ Log Analytics workspace), Container Apps, Function Apps, and all RBAC role assignments.',
      techStack: ['Azure Bicep', 'Azure RBAC', 'Managed Identity', 'Azure Container Registry'],
      endpoints: [],
      designDocs: [],
      repoUrl: 'https://github.com/skarumbu/azure-infrastructure',
    },
  },
];

export const initialEdges: ArchEdge[] = [
  {
    id: 'e-browser-spa',
    source: 'browser',
    target: 'my-website',
    data: { label: 'HTTPS', edgeType: 'browser' },
    type: 'smoothstep',
    animated: true,
    style: { stroke: '#58a6ff', strokeWidth: 2 },
    label: 'HTTPS',
  },
  {
    id: 'e-spa-digits',
    source: 'my-website',
    target: 'digits',
    data: { label: 'GET /api/DigitsGetter', edgeType: 'http' },
    type: 'smoothstep',
    style: { stroke: '#3fb950' },
    label: 'GET /api/DigitsGetter',
  },
  {
    id: 'e-spa-momentum',
    source: 'my-website',
    target: 'momentum_finder',
    data: { label: 'GET /get-current-games', edgeType: 'http' },
    type: 'smoothstep',
    style: { stroke: '#d29922' },
    label: 'GET /get-current-games',
  },
  {
    id: 'e-spa-trail',
    source: 'my-website',
    target: 'trail_finder',
    data: { label: 'GET /get-trail-recommendations', edgeType: 'http' },
    type: 'smoothstep',
    style: { stroke: '#58a6ff' },
    label: 'GET /get-trail-recommendations',
  },
  {
    id: 'e-spa-ideas',
    source: 'my-website',
    target: 'ideas_api',
    data: { label: 'GET /api/ideas', edgeType: 'http' },
    type: 'smoothstep',
    style: { stroke: '#bc8cff' },
    label: 'GET /api/ideas',
  },
  {
    id: 'e-spa-dashboard',
    source: 'my-website',
    target: 'dashboard_api',
    data: { label: 'GET /api/DashboardGetter', edgeType: 'http' },
    type: 'smoothstep',
    style: { stroke: '#bc8cff' },
    label: 'GET /api/DashboardGetter',
  },
  {
    id: 'e-ideas-bot',
    source: 'ideas_api',
    target: 'ideas_bot',
    data: { label: 'trigger job', edgeType: 'event' },
    type: 'smoothstep',
    animated: true,
    style: { stroke: '#bc8cff', strokeDasharray: '5 3' },
    label: 'trigger job',
  },
  {
    id: 'e-dash-momentum',
    source: 'dashboard_api',
    target: 'momentum_finder',
    data: { label: 'health check', edgeType: 'http' },
    type: 'smoothstep',
    style: { stroke: '#8b949e', strokeDasharray: '4 3' },
    label: 'health check',
  },
  {
    id: 'e-dash-trail',
    source: 'dashboard_api',
    target: 'trail_finder',
    data: { label: 'health check', edgeType: 'http' },
    type: 'smoothstep',
    style: { stroke: '#8b949e', strokeDasharray: '4 3' },
    label: 'health check',
  },
  {
    id: 'e-infra-spa',
    source: 'azure_infrastructure',
    target: 'my-website',
    data: { edgeType: 'storage' },
    type: 'smoothstep',
    style: { stroke: '#30363d', strokeDasharray: '6 3', opacity: 0.5 },
    label: 'provisions',
  },
  {
    id: 'e-infra-digits',
    source: 'azure_infrastructure',
    target: 'digits',
    data: { edgeType: 'storage' },
    type: 'smoothstep',
    style: { stroke: '#30363d', strokeDasharray: '6 3', opacity: 0.5 },
  },
  {
    id: 'e-infra-ideas',
    source: 'azure_infrastructure',
    target: 'ideas_api',
    data: { edgeType: 'storage' },
    type: 'smoothstep',
    style: { stroke: '#30363d', strokeDasharray: '6 3', opacity: 0.5 },
  },
  {
    id: 'e-infra-dashboard',
    source: 'azure_infrastructure',
    target: 'dashboard_api',
    data: { edgeType: 'storage' },
    type: 'smoothstep',
    style: { stroke: '#30363d', strokeDasharray: '6 3', opacity: 0.5 },
  },
];
